# Generated by Django 5.2.6 on 2025-09-19 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='courses',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
